# -*- coding: utf-8 -*-

import hashlib
import json


CONTRACT_SCHEMA_VERSION = 1
CONTRACT_CAPTURE_SOURCE_HEAD = 'd443d9f5232c9b3e0ada7c404c20a6cee977d917'
CONTRACT_CAPTURE_ARTIFACT_SHA256 = (
    '65F4E69B06941B02695BC1AA83834C7F1C1CFCDAC318073AD265408518EEF19C'
)
STATIC_FIELD_COUNT = 32

STATIC_PRODUCT_LIST_CONTRACTS = {'CPU': {'contractSha256': '46b76872f75c1d257812b03d197e6a32b5461b79293cc74b87c85e006c90ee19',
         'fields': {'addDelivery': 'N',
                    'bMakerDisplayYN': 'Y',
                    'categoryCode': '747',
                    'categoryMappingCode': '699',
                    'coupangMemberSort': '',
                    'coupangMemberSortLayerType': '',
                    'depth': '2',
                    'dnwSwitchOn': '',
                    'group': '11',
                    'isAssemblyGalleryCategory': 'Y',
                    'isDpgZoneUICategory': 'N',
                    'listCategoryCode': '747',
                    'listCount': '90',
                    'listPackageType': '3',
                    'nPackageLimit': '6',
                    'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:747;}',
                    'physicsCate1': '861',
                    'physicsCate2': '873',
                    'physicsCate3': '0',
                    'physicsCate4': '0',
                    'priceUnit': '0',
                    'priceUnitClass': '',
                    'priceUnitSort': 'N',
                    'priceUnitSortOrder': 'A',
                    'priceUnitValue': '0',
                    'quickDeliveryCategoryYN': 'N',
                    'quickDeliveryDisplay': '',
                    'sMallMinPriceDisplayYN': 'undefined',
                    'sProductListApi': 'search',
                    'simpleDescriptionDisplayYN': 'Y',
                    'simpleDescriptionOpen': 'Y',
                    'viewMethod': 'LIST'},
         'url': 'https://prod.danawa.com/list/?cate=112747'},
 'Case': {'contractSha256': 'a4169bd507a6059653a78889ef3757d1aed7d6c2c133fcbf431abf1b1621ed5b',
          'fields': {'addDelivery': 'N',
                     'bMakerDisplayYN': 'Y',
                     'categoryCode': '775',
                     'categoryMappingCode': '727',
                     'coupangMemberSort': '',
                     'coupangMemberSortLayerType': '',
                     'depth': '2',
                     'dnwSwitchOn': '',
                     'group': '11',
                     'isAssemblyGalleryCategory': 'Y',
                     'isDpgZoneUICategory': 'N',
                     'listCategoryCode': '775',
                     'listCount': '90',
                     'listPackageType': '3',
                     'nPackageLimit': '5',
                     'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:775;}',
                     'physicsCate1': '861',
                     'physicsCate2': '879',
                     'physicsCate3': '0',
                     'physicsCate4': '0',
                     'priceUnit': '0',
                     'priceUnitClass': '',
                     'priceUnitSort': 'N',
                     'priceUnitSortOrder': 'A',
                     'priceUnitValue': '0',
                     'quickDeliveryCategoryYN': 'N',
                     'quickDeliveryDisplay': '',
                     'sMallMinPriceDisplayYN': 'undefined',
                     'sProductListApi': 'search',
                     'simpleDescriptionDisplayYN': 'Y',
                     'simpleDescriptionOpen': 'Y',
                     'viewMethod': 'LIST'},
          'url': 'https://prod.danawa.com/list/?cate=112775'},
 'Cooler': {'contractSha256': '51b9e0045e51e662af36c5ae7f749d42cc62605d5f9566af70699b767df2f39e',
            'fields': {'addDelivery': 'N',
                       'bMakerDisplayYN': 'Y',
                       'categoryCode': '36855',
                       'categoryMappingCode': '48225',
                       'coupangMemberSort': '',
                       'coupangMemberSortLayerType': '',
                       'depth': '2',
                       'dnwSwitchOn': '',
                       'group': '11',
                       'isAssemblyGalleryCategory': 'Y',
                       'isDpgZoneUICategory': 'N',
                       'listCategoryCode': '36855',
                       'listCount': '90',
                       'listPackageType': '3',
                       'nPackageLimit': '6',
                       'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:36855;}',
                       'physicsCate1': '862',
                       'physicsCate2': '887',
                       'physicsCate3': '0',
                       'physicsCate4': '0',
                       'priceUnit': '0',
                       'priceUnitClass': '',
                       'priceUnitSort': 'N',
                       'priceUnitSortOrder': 'A',
                       'priceUnitValue': '0',
                       'quickDeliveryCategoryYN': 'N',
                       'quickDeliveryDisplay': '',
                       'sMallMinPriceDisplayYN': 'undefined',
                       'sProductListApi': 'search',
                       'simpleDescriptionDisplayYN': 'N',
                       'simpleDescriptionOpen': 'Y',
                       'viewMethod': 'LIST'},
            'url': 'https://prod.danawa.com/list/?cate=11236855'},
 'Earphone': {'contractSha256': '848d82de8fb64c5318bc2cc10ea03d43ec1467ff8aa3c07549e00487d5dcbe05',
              'fields': {'addDelivery': 'N',
                         'bMakerDisplayYN': 'Y',
                         'categoryCode': '52571',
                         'categoryMappingCode': '72882',
                         'coupangMemberSort': '',
                         'coupangMemberSortLayerType': '',
                         'depth': '2',
                         'dnwSwitchOn': '',
                         'group': '11',
                         'isAssemblyGalleryCategory': 'N',
                         'isDpgZoneUICategory': 'N',
                         'listCategoryCode': '52571',
                         'listCount': '90',
                         'listPackageType': '1',
                         'nPackageLimit': '5',
                         'oCurrentCategoryCode': 'a:2:{i:1;i:52449;i:2;i:52571;}',
                         'physicsCate1': '224',
                         'physicsCate2': '49729',
                         'physicsCate3': '49740',
                         'physicsCate4': '0',
                         'priceUnit': '0',
                         'priceUnitClass': '',
                         'priceUnitSort': 'N',
                         'priceUnitSortOrder': 'A',
                         'priceUnitValue': '0',
                         'quickDeliveryCategoryYN': 'N',
                         'quickDeliveryDisplay': '로켓배송',
                         'sMallMinPriceDisplayYN': 'undefined',
                         'sProductListApi': 'search',
                         'simpleDescriptionDisplayYN': 'N',
                         'simpleDescriptionOpen': 'Y',
                         'viewMethod': 'LIST'},
              'url': 'https://prod.danawa.com/list/?cate=11252571'},
 'HDD': {'contractSha256': '869b4433b873d41476c68d28f1c36ed2427fcd9182419a929a35e35f2e544d92',
         'fields': {'addDelivery': 'N',
                    'bMakerDisplayYN': 'Y',
                    'categoryCode': '763',
                    'categoryMappingCode': '714',
                    'coupangMemberSort': '',
                    'coupangMemberSortLayerType': '',
                    'depth': '2',
                    'dnwSwitchOn': '',
                    'group': '11',
                    'isAssemblyGalleryCategory': 'N',
                    'isDpgZoneUICategory': 'N',
                    'listCategoryCode': '763',
                    'listCount': '90',
                    'listPackageType': '1',
                    'nPackageLimit': '6',
                    'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:763;}',
                    'physicsCate1': '861',
                    'physicsCate2': '877',
                    'physicsCate3': '0',
                    'physicsCate4': '0',
                    'priceUnit': '1',
                    'priceUnitClass': '',
                    'priceUnitSort': 'Y',
                    'priceUnitSortOrder': 'A',
                    'priceUnitValue': '0',
                    'quickDeliveryCategoryYN': 'N',
                    'quickDeliveryDisplay': '',
                    'sMallMinPriceDisplayYN': 'undefined',
                    'sProductListApi': 'search',
                    'simpleDescriptionDisplayYN': 'N',
                    'simpleDescriptionOpen': 'Y',
                    'viewMethod': 'LIST'},
         'url': 'https://prod.danawa.com/list/?cate=112763'},
 'Headphone': {'contractSha256': '1d33c715bb82455d1f2ceae57f09c896cb71a11095b1a770b03cdbe86bffdf23',
               'fields': {'addDelivery': 'N',
                          'bMakerDisplayYN': 'Y',
                          'categoryCode': '52453',
                          'categoryMappingCode': '72665',
                          'coupangMemberSort': '',
                          'coupangMemberSortLayerType': '',
                          'depth': '2',
                          'dnwSwitchOn': '',
                          'group': '11',
                          'isAssemblyGalleryCategory': 'N',
                          'isDpgZoneUICategory': 'N',
                          'listCategoryCode': '52453',
                          'listCount': '90',
                          'listPackageType': '1',
                          'nPackageLimit': '5',
                          'oCurrentCategoryCode': 'a:2:{i:1;i:52449;i:2;i:52453;}',
                          'physicsCate1': '224',
                          'physicsCate2': '49729',
                          'physicsCate3': '0',
                          'physicsCate4': '0',
                          'priceUnit': '0',
                          'priceUnitClass': '',
                          'priceUnitSort': 'N',
                          'priceUnitSortOrder': 'A',
                          'priceUnitValue': '0',
                          'quickDeliveryCategoryYN': 'N',
                          'quickDeliveryDisplay': '',
                          'sMallMinPriceDisplayYN': 'undefined',
                          'sProductListApi': 'search',
                          'simpleDescriptionDisplayYN': 'N',
                          'simpleDescriptionOpen': 'Y',
                          'viewMethod': 'LIST'},
               'url': 'https://prod.danawa.com/list/?cate=11252453'},
 'Headset': {'contractSha256': '9d11e13010c89678607293dcbe1fbfb4e9492c30a531d9f37a83f7d238def46a',
             'fields': {'addDelivery': 'N',
                        'bMakerDisplayYN': 'Y',
                        'categoryCode': '38749',
                        'categoryMappingCode': '61366',
                        'coupangMemberSort': '',
                        'coupangMemberSortLayerType': '',
                        'depth': '2',
                        'dnwSwitchOn': '',
                        'group': '11',
                        'isAssemblyGalleryCategory': 'N',
                        'isDpgZoneUICategory': 'N',
                        'listCategoryCode': '52451',
                        'listCount': '90',
                        'listPackageType': '1',
                        'nPackageLimit': '5',
                        'oCurrentCategoryCode': 'a:2:{i:1;i:52449;i:2;i:52451;}',
                        'physicsCate1': '224',
                        'physicsCate2': '221215',
                        'physicsCate3': '221911',
                        'physicsCate4': '0',
                        'priceUnit': '0',
                        'priceUnitClass': '',
                        'priceUnitSort': 'N',
                        'priceUnitSortOrder': 'A',
                        'priceUnitValue': '0',
                        'quickDeliveryCategoryYN': 'N',
                        'quickDeliveryDisplay': '',
                        'sMallMinPriceDisplayYN': 'undefined',
                        'sProductListApi': 'search',
                        'simpleDescriptionDisplayYN': 'Y',
                        'simpleDescriptionOpen': 'Y',
                        'viewMethod': 'LIST'},
             'url': 'https://prod.danawa.com/list/?cate=11252451'},
 'Keyboard': {'contractSha256': 'a7597b6bf014e5cde5d3a470b440f7f481550281ee87f54401c15cd9360eb2d5',
              'fields': {'addDelivery': 'N',
                         'bMakerDisplayYN': 'Y',
                         'categoryCode': '782',
                         'categoryMappingCode': '734',
                         'coupangMemberSort': '',
                         'coupangMemberSortLayerType': '',
                         'depth': '2',
                         'dnwSwitchOn': '',
                         'group': '11',
                         'isAssemblyGalleryCategory': 'N',
                         'isDpgZoneUICategory': 'N',
                         'listCategoryCode': '782',
                         'listCount': '90',
                         'listPackageType': '3',
                         'nPackageLimit': '5',
                         'oCurrentCategoryCode': 'a:2:{i:2;i:782;i:1;i:53473;}',
                         'physicsCate1': '861',
                         'physicsCate2': '881',
                         'physicsCate3': '0',
                         'physicsCate4': '0',
                         'priceUnit': '0',
                         'priceUnitClass': '',
                         'priceUnitSort': 'N',
                         'priceUnitSortOrder': 'A',
                         'priceUnitValue': '0',
                         'quickDeliveryCategoryYN': 'N',
                         'quickDeliveryDisplay': '',
                         'sMallMinPriceDisplayYN': 'undefined',
                         'sProductListApi': 'search',
                         'simpleDescriptionDisplayYN': 'N',
                         'simpleDescriptionOpen': 'Y',
                         'viewMethod': 'LIST'},
              'url': 'https://prod.danawa.com/list/?cate=112782'},
 'Laptop': {'contractSha256': 'fce4c27525213d65aaaff77e6147ce334625850dabc126cc51c00c06bda3eccd',
            'fields': {'addDelivery': 'N',
                       'bMakerDisplayYN': 'Y',
                       'categoryCode': '758',
                       'categoryMappingCode': '710',
                       'coupangMemberSort': '',
                       'coupangMemberSortLayerType': '',
                       'depth': '2',
                       'dnwSwitchOn': '',
                       'group': '11',
                       'isAssemblyGalleryCategory': 'N',
                       'isDpgZoneUICategory': 'N',
                       'listCategoryCode': '758',
                       'listCount': '90',
                       'listPackageType': '3',
                       'nPackageLimit': '7',
                       'oCurrentCategoryCode': 'a:2:{i:1;i:96;i:2;i:758;}',
                       'physicsCate1': '860',
                       'physicsCate2': '869',
                       'physicsCate3': '0',
                       'physicsCate4': '0',
                       'priceUnit': '0',
                       'priceUnitClass': '',
                       'priceUnitSort': 'N',
                       'priceUnitSortOrder': 'A',
                       'priceUnitValue': '0',
                       'quickDeliveryCategoryYN': 'N',
                       'quickDeliveryDisplay': '',
                       'sMallMinPriceDisplayYN': 'undefined',
                       'sProductListApi': 'search',
                       'simpleDescriptionDisplayYN': 'Y',
                       'simpleDescriptionOpen': 'Y',
                       'viewMethod': 'LIST'},
            'url': 'https://prod.danawa.com/list/?cate=112758'},
 'MBoard': {'contractSha256': '2952a72768a158166b65cabb7b7e125b6451b81c1904aad4dd253986c954b143',
            'fields': {'addDelivery': 'N',
                       'bMakerDisplayYN': 'Y',
                       'categoryCode': '751',
                       'categoryMappingCode': '703',
                       'coupangMemberSort': '',
                       'coupangMemberSortLayerType': '',
                       'depth': '2',
                       'dnwSwitchOn': '',
                       'group': '11',
                       'isAssemblyGalleryCategory': 'Y',
                       'isDpgZoneUICategory': 'N',
                       'listCategoryCode': '751',
                       'listCount': '90',
                       'listPackageType': '1',
                       'nPackageLimit': '5',
                       'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:751;}',
                       'physicsCate1': '861',
                       'physicsCate2': '875',
                       'physicsCate3': '0',
                       'physicsCate4': '0',
                       'priceUnit': '0',
                       'priceUnitClass': '',
                       'priceUnitSort': 'N',
                       'priceUnitSortOrder': 'A',
                       'priceUnitValue': '0',
                       'quickDeliveryCategoryYN': 'N',
                       'quickDeliveryDisplay': '',
                       'sMallMinPriceDisplayYN': 'undefined',
                       'sProductListApi': 'search',
                       'simpleDescriptionDisplayYN': 'Y',
                       'simpleDescriptionOpen': 'Y',
                       'viewMethod': 'LIST'},
            'url': 'https://prod.danawa.com/list/?cate=112751'},
 'Monitor': {'contractSha256': 'a2bf6d669dde6765bcf53bb8c14845f55efbd3d4b4bafa9acbb466cfe1afedc2',
             'fields': {'addDelivery': 'N',
                        'bMakerDisplayYN': 'Y',
                        'categoryCode': '757',
                        'categoryMappingCode': '75287',
                        'coupangMemberSort': '',
                        'coupangMemberSortLayerType': '',
                        'depth': '2',
                        'dnwSwitchOn': '',
                        'group': '11',
                        'isAssemblyGalleryCategory': 'N',
                        'isDpgZoneUICategory': 'N',
                        'listCategoryCode': '757',
                        'listCount': '90',
                        'listPackageType': '3',
                        'nPackageLimit': '5',
                        'oCurrentCategoryCode': 'a:2:{i:1;i:99;i:2;i:757;}',
                        'physicsCate1': '860',
                        'physicsCate2': '13735',
                        'physicsCate3': '0',
                        'physicsCate4': '0',
                        'priceUnit': '0',
                        'priceUnitClass': '',
                        'priceUnitSort': 'N',
                        'priceUnitSortOrder': 'A',
                        'priceUnitValue': '0',
                        'quickDeliveryCategoryYN': 'N',
                        'quickDeliveryDisplay': '',
                        'sMallMinPriceDisplayYN': 'undefined',
                        'sProductListApi': 'search',
                        'simpleDescriptionDisplayYN': 'Y',
                        'simpleDescriptionOpen': 'Y',
                        'viewMethod': 'LIST'},
             'url': 'https://prod.danawa.com/list/?cate=112757'},
 'Mouse': {'contractSha256': '40ff5a26d94c437584979168f8e3f2b13231c4eb36da4a3c8306d8f9041cdeb4',
           'fields': {'addDelivery': 'N',
                      'bMakerDisplayYN': 'Y',
                      'categoryCode': '787',
                      'categoryMappingCode': '739',
                      'coupangMemberSort': '',
                      'coupangMemberSortLayerType': '',
                      'depth': '2',
                      'dnwSwitchOn': '',
                      'group': '11',
                      'isAssemblyGalleryCategory': 'N',
                      'isDpgZoneUICategory': 'N',
                      'listCategoryCode': '787',
                      'listCount': '90',
                      'listPackageType': '3',
                      'nPackageLimit': '5',
                      'oCurrentCategoryCode': 'a:2:{i:2;i:787;i:1;i:53473;}',
                      'physicsCate1': '861',
                      'physicsCate2': '902',
                      'physicsCate3': '0',
                      'physicsCate4': '0',
                      'priceUnit': '0',
                      'priceUnitClass': '',
                      'priceUnitSort': 'N',
                      'priceUnitSortOrder': 'A',
                      'priceUnitValue': '0',
                      'quickDeliveryCategoryYN': 'N',
                      'quickDeliveryDisplay': '',
                      'sMallMinPriceDisplayYN': 'undefined',
                      'sProductListApi': 'search',
                      'simpleDescriptionDisplayYN': 'N',
                      'simpleDescriptionOpen': 'Y',
                      'viewMethod': 'LIST'},
           'url': 'https://prod.danawa.com/list/?cate=112787'},
 'Power': {'contractSha256': '5c56c450664490ca883f1e16994987e295fc7127baf4aad227291bc7e783b856',
           'fields': {'addDelivery': 'N',
                      'bMakerDisplayYN': 'Y',
                      'categoryCode': '777',
                      'categoryMappingCode': '1452',
                      'coupangMemberSort': '',
                      'coupangMemberSortLayerType': '',
                      'depth': '2',
                      'dnwSwitchOn': '',
                      'group': '11',
                      'isAssemblyGalleryCategory': 'Y',
                      'isDpgZoneUICategory': 'N',
                      'listCategoryCode': '777',
                      'listCount': '90',
                      'listPackageType': '3',
                      'nPackageLimit': '5',
                      'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:777;}',
                      'physicsCate1': '861',
                      'physicsCate2': '880',
                      'physicsCate3': '0',
                      'physicsCate4': '0',
                      'priceUnit': '0',
                      'priceUnitClass': '',
                      'priceUnitSort': 'N',
                      'priceUnitSortOrder': 'A',
                      'priceUnitValue': '0',
                      'quickDeliveryCategoryYN': 'N',
                      'quickDeliveryDisplay': '',
                      'sMallMinPriceDisplayYN': 'undefined',
                      'sProductListApi': 'search',
                      'simpleDescriptionDisplayYN': 'Y',
                      'simpleDescriptionOpen': 'Y',
                      'viewMethod': 'LIST'},
           'url': 'https://prod.danawa.com/list/?cate=112777'},
 'RAM': {'contractSha256': '8949d8222ba4dd12a97009d13b94436eda30088ee83203ecfa1d5e30dbbaef7f',
         'fields': {'addDelivery': 'N',
                    'bMakerDisplayYN': 'Y',
                    'categoryCode': '752',
                    'categoryMappingCode': '704',
                    'coupangMemberSort': '',
                    'coupangMemberSortLayerType': '',
                    'depth': '2',
                    'dnwSwitchOn': '',
                    'group': '11',
                    'isAssemblyGalleryCategory': 'N',
                    'isDpgZoneUICategory': 'N',
                    'listCategoryCode': '752',
                    'listCount': '90',
                    'listPackageType': '3',
                    'nPackageLimit': '5',
                    'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:752;}',
                    'physicsCate1': '861',
                    'physicsCate2': '874',
                    'physicsCate3': '0',
                    'physicsCate4': '0',
                    'priceUnit': '1',
                    'priceUnitClass': '',
                    'priceUnitSort': 'Y',
                    'priceUnitSortOrder': 'A',
                    'priceUnitValue': '0',
                    'quickDeliveryCategoryYN': 'N',
                    'quickDeliveryDisplay': '',
                    'sMallMinPriceDisplayYN': 'undefined',
                    'sProductListApi': 'search',
                    'simpleDescriptionDisplayYN': 'N',
                    'simpleDescriptionOpen': 'Y',
                    'viewMethod': 'LIST'},
         'url': 'https://prod.danawa.com/list/?cate=112752'},
 'SSD': {'contractSha256': '6fa64a1e8a71999934c28e09712c9defa275b9fd6e9afbc6f07cccdea7f4d1f7',
         'fields': {'addDelivery': 'N',
                    'bMakerDisplayYN': 'Y',
                    'categoryCode': '760',
                    'categoryMappingCode': '711',
                    'coupangMemberSort': '',
                    'coupangMemberSortLayerType': '',
                    'depth': '2',
                    'dnwSwitchOn': '',
                    'group': '11',
                    'isAssemblyGalleryCategory': 'N',
                    'isDpgZoneUICategory': 'N',
                    'listCategoryCode': '760',
                    'listCount': '90',
                    'listPackageType': '3',
                    'nPackageLimit': '5',
                    'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:760;}',
                    'physicsCate1': '861',
                    'physicsCate2': '32617',
                    'physicsCate3': '0',
                    'physicsCate4': '0',
                    'priceUnit': '1',
                    'priceUnitClass': '',
                    'priceUnitSort': 'Y',
                    'priceUnitSortOrder': 'A',
                    'priceUnitValue': '0',
                    'quickDeliveryCategoryYN': 'N',
                    'quickDeliveryDisplay': '',
                    'sMallMinPriceDisplayYN': 'undefined',
                    'sProductListApi': 'search',
                    'simpleDescriptionDisplayYN': 'Y',
                    'simpleDescriptionOpen': 'Y',
                    'viewMethod': 'LIST'},
         'url': 'https://prod.danawa.com/list/?cate=112760'},
 'Speaker': {'contractSha256': 'ed693d388f88bed3689a02a4cc771b4aabe5c8924933a301adc6cc2dc4f7c43e',
             'fields': {'addDelivery': 'N',
                        'bMakerDisplayYN': 'Y',
                        'categoryCode': '52452',
                        'categoryMappingCode': '72659,72660,72661,72663,72664,73165',
                        'coupangMemberSort': '',
                        'coupangMemberSortLayerType': '',
                        'depth': '2',
                        'dnwSwitchOn': '',
                        'group': '11',
                        'isAssemblyGalleryCategory': 'N',
                        'isDpgZoneUICategory': 'N',
                        'listCategoryCode': '52452',
                        'listCount': '90',
                        'listPackageType': '1',
                        'nPackageLimit': '5',
                        'oCurrentCategoryCode': 'a:2:{i:1;i:52449;i:2;i:52452;}',
                        'physicsCate1': '149',
                        'physicsCate2': '221212',
                        'physicsCate3': '0',
                        'physicsCate4': '0',
                        'priceUnit': '0',
                        'priceUnitClass': '',
                        'priceUnitSort': 'N',
                        'priceUnitSortOrder': 'A',
                        'priceUnitValue': '0',
                        'quickDeliveryCategoryYN': 'N',
                        'quickDeliveryDisplay': '',
                        'sMallMinPriceDisplayYN': 'undefined',
                        'sProductListApi': 'search',
                        'simpleDescriptionDisplayYN': 'N',
                        'simpleDescriptionOpen': 'Y',
                        'viewMethod': 'LIST'},
             'url': 'https://prod.danawa.com/list/?cate=11252452'},
 'VGA': {'contractSha256': '892d91940108a0e243f52849c0a97ec53ecd408f7ab2b9b7c784871b23187e22',
         'fields': {'addDelivery': 'N',
                    'bMakerDisplayYN': 'Y',
                    'categoryCode': '753',
                    'categoryMappingCode': '705',
                    'coupangMemberSort': '',
                    'coupangMemberSortLayerType': '',
                    'depth': '2',
                    'dnwSwitchOn': '',
                    'group': '11',
                    'isAssemblyGalleryCategory': 'Y',
                    'isDpgZoneUICategory': 'N',
                    'listCategoryCode': '753',
                    'listCount': '90',
                    'listPackageType': '3',
                    'nPackageLimit': '5',
                    'oCurrentCategoryCode': 'a:2:{i:1;i:97;i:2;i:753;}',
                    'physicsCate1': '861',
                    'physicsCate2': '876',
                    'physicsCate3': '0',
                    'physicsCate4': '0',
                    'priceUnit': '0',
                    'priceUnitClass': '',
                    'priceUnitSort': 'N',
                    'priceUnitSortOrder': 'A',
                    'priceUnitValue': '0',
                    'quickDeliveryCategoryYN': 'N',
                    'quickDeliveryDisplay': '',
                    'sMallMinPriceDisplayYN': 'undefined',
                    'sProductListApi': 'search',
                    'simpleDescriptionDisplayYN': 'N',
                    'simpleDescriptionOpen': 'Y',
                    'viewMethod': 'LIST'},
         'url': 'https://prod.danawa.com/list/?cate=112753'}}


def _canonical_hash(value):
    payload = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(',', ':'),
    ).encode('utf-8')
    return hashlib.sha256(payload).hexdigest()


def GetStaticProductListFields(crawlingName, crawlingURL):
    contract = STATIC_PRODUCT_LIST_CONTRACTS.get(crawlingName)
    if contract is None:
        raise RuntimeError(f'Static Danawa contract missing: {crawlingName}')

    expectedURL = contract['url']
    if crawlingURL != expectedURL:
        raise RuntimeError(
            f'Static Danawa contract URL mismatch: {crawlingName}: '
            f'{crawlingURL!r} != {expectedURL!r}'
        )

    fields = contract['fields']
    if len(fields) != STATIC_FIELD_COUNT:
        raise RuntimeError(
            f'Static Danawa contract field count mismatch: {crawlingName}: '
            f'{len(fields)} != {STATIC_FIELD_COUNT}'
        )

    actualHash = _canonical_hash(fields)
    expectedHash = contract['contractSha256']
    if actualHash != expectedHash:
        raise RuntimeError(
            f'Static Danawa contract hash mismatch: {crawlingName}: '
            f'{actualHash} != {expectedHash}'
        )

    return dict(fields)
